fragment Cart on Cart {

  checkoutUrl

  total

  rawTotal: total(format: RAW)

  subtotal

  shippingTotal

  totalTax

  discountTotal

  rawDiscountTotal: discountTotal(format: RAW)

  needsShippingAddress

  chosenShippingMethods

  availableShippingMethods {

    rates {

      id

      label

      cost

    }

  }

  appliedCoupons {

    code

    description

    discountAmount

    discountTax

  }

  isEmpty

  contents(first:100){

    itemCount

    productCount

    nodes{

      key

      quantity

      product{

        node{

          databaseId

          name

          slug

          sku

          ...SimpleProduct

          ...VariableProduct

          ...ExternalProduct

        }

      }

      variation{

        node{

          databaseId

          name

          price

          regularPrice

          salePrice

          stockStatus

          image{

            sourceUrl(size:THUMBNAIL)

            altText

          }

        }

      }

    }

  }

}